
spring:
  datasource:
    url: jdbc:oracle:thin:@//192.168.1.230:1521/inventory_pdb.example.com
    username: inventoryuser
    password: Weblogic1
#    url: jdbc:oracle:thin:@//203.126.35.87:1521/inventory_pdb.sunright.com
#    username: inventoryuser
#    password: Ue1car0
  flyway:
    enabled: true
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: trace
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
