CREATE TABLE MSR
(	"COMPANY_CODE" VARCHAR2(3 BYTE) NOT NULL ENABLE,
     "PLANT_NO" NUMBER(3,0) NOT NULL ENABLE,
     "MSR_NO" VARCHAR2(15 BYTE) NOT NULL ENABLE,
     "VERSION" NUMBER NOT NULL,
     "SUPPLIER_CODE" VARCHAR2(10 BYTE),
     "DOCM_NO" VARCHAR2(30 BYTE),
     "BATCH_ID" VARCHAR2(15 BYTE),
     "ORIGINATOR" VARCHAR2(30 BYTE),
     "MRV_NO" VARCHAR2(15 BYTE),
     "CURRENCY_CODE" VARCHAR2(3 BYTE),
     "CURRENCY_RATE" NUMBER(10,6),
     STATUS INTEGER NOT NULL,
     CREATED_BY VARCHAR2(200) NOT NULL,
     CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
     UPDATED_BY VARCHAR2(200) NOT NULL,
     UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX MSR_PK ON MSR ("COMPANY_CODE", "PLANT_NO", "MSR_NO");

ALTER TABLE MSR ADD CONSTRAINT MSR_PK PRIMARY KEY ("COMPANY_CODE", "PLANT_NO", "MSR_NO")
    USING INDEX MSR_PK ENABLE;


CREATE TABLE MSRDET
(	"COMPANY_CODE" VARCHAR2(3 BYTE) NOT NULL ENABLE,
     "PLANT_NO" NUMBER(3,0) NOT NULL ENABLE,
     "MSR_NO" VARCHAR2(15 BYTE) NOT NULL ENABLE,
     "SEQ_NO" NUMBER(3,0) NOT NULL ENABLE,
     "ITEM_NO" VARCHAR2(15 BYTE),
     "PART_NO" VARCHAR2(60 BYTE),
     "LOC" VARCHAR2(5 BYTE),
     "ITEM_TYPE" NUMBER(2,0),
     "BATCH_NO" VARCHAR2(15 BYTE),
     "PROJECT_NO" VARCHAR2(15 BYTE),
     "GRN_TYPE" VARCHAR2(10 BYTE),
     "GRN_NO" VARCHAR2(15 BYTE),
     "GRNDET_SEQ_NO" NUMBER(3,0),
     "GRNDET_RECD_QTY" NUMBER(16,4),
     "SUPPLIER_RETN" VARCHAR2(1 BYTE),
     "RETN_QTY" NUMBER(16,4),
     "RETN_PRICE" NUMBER(16,4),
     "RETN_TYPE" VARCHAR2(2 BYTE),
     "RETN_ACTION" VARCHAR2(2 BYTE),
     "UOM" VARCHAR2(3 BYTE),
     "RECD_QTY" NUMBER(16,4),
     "RECD_PRICE" NUMBER(16,4),
     "CURRENCY_CODE" VARCHAR2(3 BYTE),
     "CURRENCY_RATE" NUMBER(10,6),
     "MRV_NO" VARCHAR2(15 BYTE),
     "REMARKS" VARCHAR2(2000 BYTE),
     CONSTRAINT "MSRDET_FK" FOREIGN KEY ("COMPANY_CODE", "PLANT_NO", "MSR_NO")
         REFERENCES MSR ("COMPANY_CODE", "PLANT_NO", "MSR_NO") ENABLE
);

CREATE UNIQUE INDEX MSRDET_PK ON MSRDET ("COMPANY_CODE", "PLANT_NO", "MSR_NO", "SEQ_NO");

ALTER TABLE MSRDET ADD CONSTRAINT MSRDET_PK PRIMARY KEY ("COMPANY_CODE", "PLANT_NO", "MSR_NO", "SEQ_NO")
    USING INDEX MSRDET_PK ENABLE;

