
DROP TABLE ITEMBATC;

CREATE TABLE "ITEMBATC"
(	"COMPANY_CODE" VARCHAR2(3 BYTE) NOT NULL ENABLE,
     "PLANT_NO" NUMBER(3,0) NOT NULL ENABLE,
     "ITEM_NO" VARCHAR2(15 BYTE) NOT NULL ENABLE,
     "LOC" VARCHAR2(5 BYTE) NOT NULL ENABLE,
     "BATCH_NO" NUMBER(8,0) NOT NULL ENABLE,
     "TRAN_DATE" DATE,
     "DATE_CODE" NUMBER(4,0),
     "PO_NO" VARCHAR2(15 BYTE),
     "PO_REC_SEQ" NUMBER(3,0),
     "GRN_NO" VARCHAR2(15 BYTE),
     "GRN_SEQ" NUMBER(3,0),
     "QOH" NUMBER(16,4),
     "ORI_QOH" NUMBER(16,4),
     "STD_SETUP" NUMBER(16,4),
     "STD_MATERIAL" NUMBER(16,4),
     "STD_LABOR" NUMBER(16,4),
     "STD_BURDEN" NUMBER(16,4),
     "STD_SUBCONTRACT" NUMBER(16,4),
     "STD_MACHINE" NUMBER(16,4)
);

CREATE UNIQUE INDEX ITEMBATC_PK ON ITEMBATC ("COMPANY_CODE", "PLANT_NO", "ITEM_NO", "LOC", "BATCH_NO");

ALTER TABLE "ITEMBATC" ADD CONSTRAINT "ITEMBATC_PK" PRIMARY KEY ("COMPANY_CODE", "PLANT_NO", "ITEM_NO", "LOC", "BATCH_NO")
    USING INDEX "ITEMBATC_PK"  ENABLE;