----------------------------------------------- SIV -----------------------------------------------

CREATE TABLE SIV
(
    "ID"            NUMBER(20, 0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    "COMPANY_CODE"  VARCHAR2(3 BYTE)                                   NOT NULL ENABLE,
    "PLANT_NO"      NUMBER(3, 0)                                       NOT NULL ENABLE,
    "SUB_TYPE"      VARCHAR2(10 BYTE)                                  NOT NULL ENABLE,
    "SIV_NO"        VARCHAR2(15 BYTE)                                  NOT NULL ENABLE,
    "PROJECT_NO"    VARCHAR2(15 BYTE),
    "CURRENCY_CODE" VARCHAR2(3 BYTE),
    "CURRENCY_RATE" NUMBER(10, 6),
    "STATUS_1"      VARCHAR2(1 BYTE),
    "ENTRY_TIME"    VARCHAR2(10 BYTE),
    "TRAN_TYPE"     VARCHAR2(5 BYTE),
    "DOCM_NO"       VARCHAR2(15 BYTE),
    STATUS          INTEGER                  DEFAULT 1                 NOT NULL,
    CREATED_BY      VARCHAR2(200)            DEFAULT 'system'          NOT NULL,
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_BY      VARCHAR2(200)            DEFAULT 'system'          NOT NULL,
    UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX SIV_PK ON SIV ("ID");

ALTER TABLE SIV
    ADD CONSTRAINT SIV_PK PRIMARY KEY ("ID")
        USING INDEX SIV_PK ENABLE;

CREATE UNIQUE INDEX UNIQUE_SIV_IDX ON SIV ("COMPANY_CODE", "PLANT_NO", "SIV_NO");

----------------------------------------------- SIVDET -----------------------------------------------

CREATE TABLE SIVDET
(
    "ID"                NUMBER(20, 0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    "SIV_ID"            NUMBER(20, 0)     NOT NULL ENABLE,
    "COMPANY_CODE"      VARCHAR2(3 BYTE)  NOT NULL ENABLE,
    "PLANT_NO"          NUMBER(3, 0)      NOT NULL ENABLE,
    "SUB_TYPE"          VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "SIV_NO"            VARCHAR2(15 BYTE) NOT NULL ENABLE,
    "SEQ_NO"            NUMBER(3, 0)      NOT NULL ENABLE,
    "ITEM_NO"           VARCHAR2(15 BYTE),
    "PART_NO"           VARCHAR2(60 BYTE),
    "LOC"               VARCHAR2(5 BYTE),
    "ITEM_TYPE"         NUMBER(2, 0),
    "UOM"               VARCHAR2(3 BYTE),
    "BATCH_NO"          NUMBER(8, 0),
    "PO_NO"             VARCHAR2(15 BYTE),
    "PR_NO"             VARCHAR2(15 BYTE),
    "GRN_NO"            VARCHAR2(15 BYTE),
    "GRNDET_SEQ_NO"     NUMBER(3, 0),
    "GRNDET_RECD_PRICE" NUMBER(16, 4),
    "ISSUED_QTY"        NUMBER(16, 4),
    "ISSUED_PRICE"      NUMBER(16, 4),
    "SALE_TYPE"         VARCHAR2(1 BYTE),
    "DOCM_NO"           VARCHAR2(15 BYTE),
    "EXTRA_QTY"         NUMBER(16, 4),
    "REMARKS"           VARCHAR2(2000 BYTE),
    CONSTRAINT "SIVDET_FK" FOREIGN KEY ("SIV_ID")
        REFERENCES SIV ("ID") ENABLE
);

CREATE UNIQUE INDEX SIVDET_PK ON SIVDET ("ID");

ALTER TABLE SIVDET
    ADD CONSTRAINT SIVDET_PK PRIMARY KEY ("ID")
        USING INDEX SIVDET_PK ENABLE;

CREATE UNIQUE INDEX UNIQUE_SIVDET_IDX ON SIVDET ("COMPANY_CODE", "PLANT_NO", "SIV_NO", "SEQ_NO");

