DROP TABLE BOMBYPJ;

DROP TABLE BOMBYPJ_DET;

------------------ BOMBYPJ TABLE ------------------

CREATE TABLE BOMBYPJ
(
    "COMPANY_CODE"    VARCHAR2(3 BYTE)  NOT NULL ENABLE,
    "PLANT_NO"        NUMBER(3, 0)      NOT NULL ENABLE,
    "TRAN_TYPE"       VARCHAR2(5 BYTE)  NOT NULL ENABLE,
    "PROJECT_NO"      VARCHAR2(15 BYTE) NOT NULL ENABLE,
    "ORDER_NO"        VARCHAR2(15 BYTE) NOT NULL ENABLE,
    "ASSEMBLY_NO"     VARCHAR2(15 BYTE) NOT NULL ENABLE,
    "COMPONENT"       VARCHAR2(15 BYTE) NOT NULL ENABLE,
    "ALTERNATE"       VARCHAR2(15 BYTE) NOT NULL ENABLE,
    "SEQ_NO"          NUMBER(3, 0),
    "REQD_QTY"        NUMBER(16, 4),
    "RESV_QTY"        NUMBER(16, 4),
    "SHORT_QTY"       NUMBER(16, 4),
    "ORDER_QTY"       NUMBER(16, 4),
    "IN_TRANSIT_QTY"  NUMBER(16, 4),
    "DELV_QTY"        NUMBER(16, 4),
    "OUTSTANDING_QTY" NUMBER(16, 4),
    "ISSUED_QTY"      NUMBER(16, 4),
    "DELV_DATE"       DATE,
    "UOM"             VARCHAR2(3 BYTE),
    "STATUS"          VARCHAR2(1 BYTE),
    "PICKED_QTY"      NUMBER(16, 4),
    "MRP_STATUS"      VARCHAR2(1 BYTE),
    "BUYLIST_STATUS"  VARCHAR2(1 BYTE),
    "RESV_STATUS"     VARCHAR2(1 BYTE),
    "SRP_TYPE"        VARCHAR2(5 BYTE),
    "MRV_RESV"        NUMBER(16, 4),
    "MRV_QTY"         NUMBER(16, 4),
    "QTY_PER_ASSM"    NUMBER(16, 4),
    "RPC_NO"          VARCHAR2(15 BYTE),
    "RPC_RESV"        NUMBER(16, 4),
    "EQV_STATUS"      VARCHAR2(1 BYTE),
    "LOC"             VARCHAR2(5 BYTE)
);

CREATE UNIQUE INDEX BOMBYPJ_PK ON BOMBYPJ ("COMPANY_CODE", "PLANT_NO", "PROJECT_NO", "ORDER_NO", "ASSEMBLY_NO",
                                           "COMPONENT", "ALTERNATE");

ALTER TABLE BOMBYPJ
    ADD CONSTRAINT BOMBYPJ_PK PRIMARY KEY ("COMPANY_CODE", "PLANT_NO", "PROJECT_NO", "ORDER_NO", "ASSEMBLY_NO",
                                           "COMPONENT", "ALTERNATE") USING INDEX BOMBYPJ_PK ENABLE;

CREATE INDEX BOMBYPJ_IDX1 ON BOMBYPJ ("COMPANY_CODE", "PLANT_NO", "PROJECT_NO", "ORDER_NO", "ASSEMBLY_NO", "ALTERNATE");

CREATE INDEX BOMBYPJ_IDX2 ON BOMBYPJ ("COMPANY_CODE", "PLANT_NO", "PROJECT_NO", "ORDER_NO", "ASSEMBLY_NO", "COMPONENT");

CREATE INDEX BOMBYPJ_IDX3 ON BOMBYPJ ("COMPANY_CODE", "PLANT_NO", "PROJECT_NO", "ORDER_NO", "ASSEMBLY_NO", "ALTERNATE",
                                      "LOC");

------------------ BOMBYPJ_DET TABLE ------------------

CREATE TABLE BOMBYPJ_DET
(
    "COMPANY_CODE"   VARCHAR2(3 BYTE)  NOT NULL ENABLE,
    "PLANT_NO"       NUMBER(3, 0)      NOT NULL ENABLE,
    "TRAN_TYPE"      VARCHAR2(5 BYTE)  NOT NULL ENABLE,
    "PROJECT_NO"     VARCHAR2(15 BYTE) NOT NULL ENABLE,
    "ORDER_NO"       VARCHAR2(15 BYTE) NOT NULL ENABLE,
    "ASSEMBLY_NO"    VARCHAR2(15 BYTE) NOT NULL ENABLE,
    "COMPONENT"      VARCHAR2(15 BYTE) NOT NULL ENABLE,
    "ALTERNATE"      VARCHAR2(15 BYTE) NOT NULL ENABLE,
    "PO_NO"          VARCHAR2(15 BYTE) NOT NULL ENABLE,
    "SEQ_NO"         NUMBER(3, 0),
    "RESV_QTY"       NUMBER(16, 4),
    "ACCUM_RECD_QTY" NUMBER(16, 4),
    "RECD_QTY"       NUMBER(16, 4),
    "STATUS"         VARCHAR2(1 BYTE),
    "GRN_NO"         VARCHAR2(15 BYTE)
);

CREATE INDEX BOMBYPJ_DET_IDX1 ON BOMBYPJ_DET ("COMPANY_CODE", "PLANT_NO", "PROJECT_NO", "ORDER_NO", "ASSEMBLY_NO",
                                              "ALTERNATE");

