DROP TABLE BANK_PAYEE;
DROP TABLE SUPPLIER;
DROP TABLE COMPANY;

------------------ COMPANY TABLE ------------------

CREATE TABLE COMPANY
(
    "COMPANY_CODE"     VARCHAR2(3 BYTE) NOT NULL ENABLE,
    "PLANT_NO"         NUMBER(3, 0)     NOT NULL ENABLE,
    "COMPANY_NAME"     VARCHAR2(45 BYTE),
    "PLANT_NAME"       VARCHAR2(45 BYTE),
    "NAME_SHORT"       VARCHAR2(10 BYTE),
    "ADDRESS1"         VARCHAR2(30 BYTE),
    "ADDRESS2"         VARCHAR2(30 BYTE),
    "ADDRESS3"         VARCHAR2(30 BYTE),
    "ADDRESS4"         VARCHAR2(30 BYTE),
    "PCODE"            VARCHAR2(15 BYTE),
    "TEL_NO"           VARCHAR2(15 BYTE),
    "TEL_NO2"          VARCHAR2(15 BYTE),
    "FAX_NO"           VARCHAR2(15 BYTE),
    "FAX_NO2"          VARCHAR2(15 BYTE),
    "CURRENCY_CODE"    VARCHAR2(3 BYTE) NOT NULL ENABLE,
    "BUSINESS_NATURE"  VARCHAR2(20 BYTE),
    "COUNTRY_CODE"     VARCHAR2(10 BYTE),
    "COUNTRY_NAME"     VARCHAR2(45 BYTE),
    "REGION_CODE"      VARCHAR2(10 BYTE),
    "REGION_NAME"      VARCHAR2(45 BYTE),
    "STATE_CODE"       VARCHAR2(10 BYTE),
    "STATE_NAME"       VARCHAR2(45 BYTE),
    "STOCK_LOC"        VARCHAR2(5 BYTE),
    "DATE_FORMAT"      VARCHAR2(2 BYTE),
    "ACCESS_IN"        VARCHAR2(2 BYTE),
    "ACCESS_BOM"       VARCHAR2(2 BYTE),
    "ACCESS_MRP"       VARCHAR2(2 BYTE),
    "ACCESS_WC"        VARCHAR2(2 BYTE),
    "ACCESS_CRP"       VARCHAR2(2 BYTE),
    "ACCESS_MPS"       VARCHAR2(2 BYTE),
    "ACCESS_SFC"       VARCHAR2(2 BYTE),
    "ACCESS_CA"        VARCHAR2(2 BYTE),
    "ACCESS_SOP"       VARCHAR2(2 BYTE),
    "ACCESS_PUR"       VARCHAR2(2 BYTE),
    "ACCESS_NL"        VARCHAR2(2 BYTE),
    "ACCESS_SL"        VARCHAR2(2 BYTE),
    "ACCESS_PL"        VARCHAR2(2 BYTE),
    "ACCESS_PR"        VARCHAR2(2 BYTE),
    "ACCESS_CAD"       VARCHAR2(2 BYTE),
    "ACCESS_ST"        VARCHAR2(2 BYTE),
    "ACCESS_LOT"       VARCHAR2(2 BYTE),
    "ACCESS_EX"        VARCHAR2(2 BYTE),
    "ACCESS_FA"        VARCHAR2(2 BYTE),
    "ACCESS_PER"       VARCHAR2(2 BYTE),
    "ACCESS_UTIL"      VARCHAR2(2 BYTE),
    "TRADER_CODE"      VARCHAR2(20 BYTE),
    "TAX_REGN_NO"      VARCHAR2(20 BYTE),
    "FREIGHT_PERCENT"  NUMBER(8, 4),
    "HANDLING_PERCENT" NUMBER(8, 4),
    "INVOICE_TITLE"    VARCHAR2(20 BYTE),
    "PASSWORD_CHANGE"  NUMBER(3, 0),
    "BUSINESS_REGN_NO" VARCHAR2(20 BYTE),
    "ACCESS_CP"        VARCHAR2(2 BYTE),
    "TAX_CAT"          VARCHAR2(10 BYTE),
    "PRODUCT_VERSION"  VARCHAR2(10 BYTE),
    "GAF_VERSION"      VARCHAR2(10 BYTE),
    "CURRENCY_DECIMAL" NUMBER(3, 0),
    "TZNAME"           VARCHAR2(64 BYTE),
    "SYSTEM_EMAIL"     VARCHAR2(100 BYTE)
);

CREATE UNIQUE INDEX COMPANY_PK ON COMPANY ("COMPANY_CODE", "PLANT_NO");

ALTER TABLE COMPANY
    ADD CONSTRAINT COMPANY_PK PRIMARY KEY ("COMPANY_CODE", "PLANT_NO")
        USING INDEX COMPANY_PK ENABLE;

------------------ SUPPLIER TABLE ------------------

CREATE TABLE SUPPLIER
(
    "SUPPLIER_CODE"    VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "COMPANY_CODE"     VARCHAR2(3 BYTE)  NOT NULL ENABLE,
    "PLANT_NO"         NUMBER(3, 0)      NOT NULL ENABLE,
    "NAME"             VARCHAR2(45 BYTE),
    "ADDRESS1"         VARCHAR2(30 BYTE),
    "ADDRESS2"         VARCHAR2(30 BYTE),
    "ADDRESS3"         VARCHAR2(30 BYTE),
    "ADDRESS4"         VARCHAR2(30 BYTE),
    "PCODE"            VARCHAR2(15 BYTE),
    "TEL_NO"           VARCHAR2(15 BYTE),
    "FAX_NO"           VARCHAR2(15 BYTE),
    "CONTACT"          VARCHAR2(45 BYTE),
    "CONTACT_POSITION" VARCHAR2(30 BYTE),
    "BUYER"            VARCHAR2(20 BYTE),
    "CURRENCY_CODE"    VARCHAR2(3 BYTE),
    "CREDIT_LIMIT"     NUMBER(14, 2),
    "PAYMENT_TERM"     NUMBER(3, 0),
    "SHIPPING_TERM"    VARCHAR2(30 BYTE),
    "LAST_TRAN_AMT"    NUMBER(14, 2),
    "LAST_TRAN_DATE"   DATE,
    "BALBF"            NUMBER(14, 2),
    "DIV_CODE"         VARCHAR2(2 BYTE),
    "DEPT_CODE"        VARCHAR2(3 BYTE),
    "LOCAL_OR_FOREIGN" VARCHAR2(1 BYTE),
    "GST_NO"           VARCHAR2(20 BYTE),
    "REMARKS"          VARCHAR2(2000 BYTE),
    "PUR_AMT1"         NUMBER(14, 2),
    "PUR_AMT2"         NUMBER(14, 2),
    "PUR_AMT3"         NUMBER(14, 2),
    "PUR_AMT4"         NUMBER(14, 2),
    "PUR_AMT5"         NUMBER(14, 2),
    "PUR_AMT6"         NUMBER(14, 2),
    "PUR_AMT7"         NUMBER(14, 2),
    "PUR_AMT8"         NUMBER(14, 2),
    "PUR_AMT9"         NUMBER(14, 2),
    "PUR_AMT10"        NUMBER(14, 2),
    "PUR_AMT11"        NUMBER(14, 2),
    "PUR_AMT12"        NUMBER(14, 2),
    "PAY_AMT1"         NUMBER(14, 2),
    "PAY_AMT2"         NUMBER(14, 2),
    "PAY_AMT3"         NUMBER(14, 2),
    "PAY_AMT4"         NUMBER(14, 2),
    "PAY_AMT5"         NUMBER(14, 2),
    "PAY_AMT6"         NUMBER(14, 2),
    "PAY_AMT7"         NUMBER(14, 2),
    "PAY_AMT8"         NUMBER(14, 2),
    "PAY_AMT9"         NUMBER(14, 2),
    "PAY_AMT10"        NUMBER(14, 2),
    "PAY_AMT11"        NUMBER(14, 2),
    "PAY_AMT12"        NUMBER(14, 2),
    "SUPPLIER_TYPE"    VARCHAR2(1 BYTE),
    "COUNTRY_CODE"     VARCHAR2(10 BYTE),
    "AREA_CODE"        VARCHAR2(3 BYTE),
    "SUPPLIER_CAT"     VARCHAR2(1 BYTE),
    "COMPANY_CODE_SUB" VARCHAR2(3 BYTE),
    "PLANT_NO_SUB"     NUMBER(3, 0),
    "MOBILE_NO"        VARCHAR2(30 BYTE),
    "EMAIL_ADDRESS"    VARCHAR2(100 BYTE),
    "SUPPLIER_BRN"     VARCHAR2(30 BYTE),
    "TAX_TYPE"         VARCHAR2(10 BYTE),
    "PAYTO_ADDRESS1"   VARCHAR2(30 BYTE),
    "PAYTO_ADDRESS2"   VARCHAR2(30 BYTE),
    "PAYTO_ADDRESS3"   VARCHAR2(30 BYTE),
    "PAYTO_ADDRESS4"   VARCHAR2(30 BYTE),
    "PAYTO_PCODE"      VARCHAR2(15 BYTE),
    "SHIPTO_CODE"      VARCHAR2(15 BYTE),
    CONSTRAINT SUPPLIER_COMPANY_FK FOREIGN KEY ("COMPANY_CODE", "PLANT_NO")
        REFERENCES COMPANY ("COMPANY_CODE", "PLANT_NO") ENABLE
);

CREATE UNIQUE INDEX SUPPLIER_PK ON SUPPLIER ("COMPANY_CODE", "PLANT_NO", "SUPPLIER_CODE");

ALTER TABLE SUPPLIER
    ADD CONSTRAINT SUPPLIER_PK PRIMARY KEY ("COMPANY_CODE", "PLANT_NO", "SUPPLIER_CODE")
        USING INDEX SUPPLIER_PK ENABLE;

------------------ BANK_PAYEE TABLE ------------------

CREATE TABLE BANK_PAYEE
(
    "SUPPLIER_CODE"          VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "COMPANY_CODE"           VARCHAR2(3 BYTE)  NOT NULL ENABLE,
    "PLANT_NO"               NUMBER(3, 0)      NOT NULL ENABLE,
    "BANK_ACCOUNT_NO"        VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "BANK_ACCOUNT_NAME"      VARCHAR2(45 BYTE),
    "BANK_CODE_PAYEE"        VARCHAR2(15 BYTE),
    "BRANCH_CODE"            VARCHAR2(10 BYTE),
    "CLEARING_CODE_FOR_TT"   VARCHAR2(40 BYTE),
    "INTERMEDIARY_BANK_CODE" VARCHAR2(15 BYTE),
    "NAME1"                  VARCHAR2(45 BYTE),
    "NAME2"                  VARCHAR2(45 BYTE),
    "ADDRESS1"               VARCHAR2(30 BYTE),
    "ADDRESS2"               VARCHAR2(30 BYTE),
    "ADDRESS3"               VARCHAR2(30 BYTE),
    "ADDRESS4"               VARCHAR2(30 BYTE),
    "REMARKS1"               VARCHAR2(70 BYTE),
    "REMARKS2"               VARCHAR2(70 BYTE),
    CONSTRAINT BP_SUPPLIER_FK FOREIGN KEY ("COMPANY_CODE", "PLANT_NO", "SUPPLIER_CODE")
        REFERENCES SUPPLIER ("COMPANY_CODE", "PLANT_NO", "SUPPLIER_CODE") ENABLE
);

CREATE UNIQUE INDEX BANK_PAYEE_PK ON BANK_PAYEE ("SUPPLIER_CODE", "COMPANY_CODE", "PLANT_NO", "BANK_ACCOUNT_NO");

ALTER TABLE BANK_PAYEE
    ADD CONSTRAINT BANK_PAYEE_PK PRIMARY KEY ("SUPPLIER_CODE", "COMPANY_CODE", "PLANT_NO", "BANK_ACCOUNT_NO")
        USING INDEX BANK_PAYEE_PK ENABLE;

----------------------------------------------- NLCTL -----------------------------------------------

CREATE TABLE NLCTL
(
    "COMPANY_CODE"        VARCHAR2(3 BYTE) NOT NULL ENABLE,
    "PLANT_NO"            NUMBER(3, 0)     NOT NULL ENABLE,
    "START_PERIOD"        DATE,
    "START_MONTH"         NUMBER(2, 0),
    "START_YEAR"          NUMBER(4, 0),
    "CURRENT_FIN_MONTH"   NUMBER(2, 0),
    "CURRENT_FIN_YEAR"    NUMBER(4, 0),
    "ASSET_FR"            VARCHAR2(10 BYTE),
    "ASSET_TO"            VARCHAR2(10 BYTE),
    "LIABILITY_FR"        VARCHAR2(10 BYTE),
    "LIABILITY_TO"        VARCHAR2(10 BYTE),
    "REVENUE_FR"          VARCHAR2(10 BYTE),
    "REVENUE_TO"          VARCHAR2(10 BYTE),
    "EXPENSE_FR"          VARCHAR2(10 BYTE),
    "EXPENSE_TO"          VARCHAR2(10 BYTE),
    "MFG_EXPENSE_FR"      VARCHAR2(10 BYTE),
    "MFG_EXPENSE_TO"      VARCHAR2(10 BYTE),
    "ADM_EXPENSE_FR"      VARCHAR2(10 BYTE),
    "ADM_EXPENSE_TO"      VARCHAR2(10 BYTE),
    "CAPITAL_FR"          VARCHAR2(10 BYTE),
    "CAPITAL_TO"          VARCHAR2(10 BYTE),
    "CURRENT_PROFIT_LOSS" VARCHAR2(10 BYTE),
    "GROSS_PROFIT"        VARCHAR2(10 BYTE),
    "NET_PROFIT_LOSS"     VARCHAR2(10 BYTE),
    "USER1"               VARCHAR2(30 BYTE),
    "BATCH_NO1"           NUMBER(2, 0),
    "TRAN_NO1"            NUMBER(5, 0),
    "USER2"               VARCHAR2(30 BYTE),
    "BATCH_NO2"           NUMBER(2, 0),
    "TRAN_NO2"            NUMBER(5, 0),
    "USER3"               VARCHAR2(30 BYTE),
    "BATCH_NO3"           NUMBER(2, 0),
    "TRAN_NO3"            NUMBER(5, 0),
    "USER4"               VARCHAR2(30 BYTE),
    "BATCH_NO4"           NUMBER(2, 0),
    "TRAN_NO4"            NUMBER(5, 0),
    "USER5"               VARCHAR2(30 BYTE),
    "BATCH_NO5"           NUMBER(2, 0),
    "TRAN_NO5"            NUMBER(5, 0),
    "USER6"               VARCHAR2(30 BYTE),
    "BATCH_NO6"           NUMBER(2, 0),
    "TRAN_NO6"            NUMBER(5, 0),
    "USER7"               VARCHAR2(30 BYTE),
    "BATCH_NO7"           NUMBER(2, 0),
    "TRAN_NO7"            NUMBER(5, 0),
    "USER8"               VARCHAR2(30 BYTE),
    "BATCH_NO8"           NUMBER(2, 0),
    "TRAN_NO8"            NUMBER(5, 0),
    "USER9"               VARCHAR2(30 BYTE),
    "BATCH_NO9"           NUMBER(2, 0),
    "TRAN_NO9"            NUMBER(5, 0),
    "USER10"              VARCHAR2(30 BYTE),
    "BATCH_NO10"          NUMBER(2, 0),
    "TRAN_NO10"           NUMBER(5, 0),
    "EOP_FLAG"            VARCHAR2(1 BYTE),
    "EOY_FLAG"            VARCHAR2(1 BYTE),
    "GST_START_DATE"      DATE,
    "GST_STD_PCT"         NUMBER(5, 2),
    "GST_ZRO_PCT"         NUMBER(5, 2),
    "GST_O_STD_ACCT_CODE" VARCHAR2(10 BYTE),
    "GST_O_ZRO_ACCT_CODE" VARCHAR2(10 BYTE),
    "GST_O_STD_MEMO_CODE" VARCHAR2(10 BYTE),
    "GST_O_ZRO_MEMO_CODE" VARCHAR2(10 BYTE),
    "GST_O_EXM_MEMO_CODE" VARCHAR2(10 BYTE),
    "GST_O_OUT_MEMO_CODE" VARCHAR2(10 BYTE),
    "GST_I_STD_ACCT_CODE" VARCHAR2(10 BYTE),
    "GST_I_ZRO_ACCT_CODE" VARCHAR2(10 BYTE),
    "GST_I_STD_MEMO_CODE" VARCHAR2(10 BYTE),
    "GST_I_ZRO_MEMO_CODE" VARCHAR2(10 BYTE),
    "GST_I_EXM_MEMO_CODE" VARCHAR2(10 BYTE),
    "GST_I_OUT_MEMO_CODE" VARCHAR2(10 BYTE),
    "STOCK_ACCT_CODE"     VARCHAR2(10 BYTE),
    "STOCK_DEPT_CODE"     VARCHAR2(3 BYTE),
    "STOCK_DIV_CODE"      VARCHAR2(2 BYTE),
    "WIP_ACCT_CODE"       VARCHAR2(10 BYTE),
    "WIP_DEPT_CODE"       VARCHAR2(3 BYTE),
    "WIP_DIV_CODE"        VARCHAR2(2 BYTE),
    "ACCRUED_ACCT_CODE"   VARCHAR2(10 BYTE),
    "ACCRUED_DEPT_CODE"   VARCHAR2(3 BYTE),
    "ACCRUED_DIV_CODE"    VARCHAR2(2 BYTE),
    "INVENTORY_ENABLED"   VARCHAR2(1 BYTE),
    "INVENTORY_MONTH"     NUMBER(2, 0),
    "INVENTORY_YEAR"      NUMBER(4, 0),
    "OTHER_INCOME_FR"     VARCHAR2(10 BYTE),
    "OTHER_INCOME_TO"     VARCHAR2(10 BYTE),
    "RECOVERY_FR"         VARCHAR2(10 BYTE),
    "RECOVERY_TO"         VARCHAR2(10 BYTE),
    "TAXATION_FR"         VARCHAR2(10 BYTE),
    "TAXATION_TO"         VARCHAR2(10 BYTE),
    "COUNT_ENABLED"       VARCHAR2(1 BYTE),
    "GST_ACCT_CODE"       VARCHAR2(10 BYTE),
    "INPUT_TAX_FR"        VARCHAR2(10 BYTE),
    "INPUT_TAX_TO"        VARCHAR2(10 BYTE),
    "OUTPUT_TAX_FR"       VARCHAR2(10 BYTE),
    "OUTPUT_TAX_TO"       VARCHAR2(10 BYTE),
    "BILL_RECEIVABLE_FR"  VARCHAR2(10 BYTE),
    "BILL_RECEIVABLE_TO"  VARCHAR2(10 BYTE),
    "ACCRUED_SALES_ACCT"  VARCHAR2(10 BYTE),
    "ACCRUED_SALES_DEPT"  VARCHAR2(3 BYTE),
    "ACCRUED_SALES_DIV"   VARCHAR2(2 BYTE),
    "ST_HP_INT_ACCT"      VARCHAR2(10 BYTE),
    "ST_HP_INT_DEPT"      VARCHAR2(3 BYTE),
    "ST_HP_INT_DIV"       VARCHAR2(2 BYTE),
    "LT_HP_INT_ACCT"      VARCHAR2(10 BYTE),
    "LT_HP_INT_DEPT"      VARCHAR2(3 BYTE),
    "LT_HP_INT_DIV"       VARCHAR2(2 BYTE),
    "TAX_WITHHOLD_ACCT"   VARCHAR2(10 BYTE),
    "TAX_WITHHOLD_DEPT"   VARCHAR2(3 BYTE),
    "TAX_WITHHOLD_DIV"    VARCHAR2(2 BYTE),
    "TAX_RECOVER_ACCT"    VARCHAR2(10 BYTE),
    "TAX_RECOVER_DEPT"    VARCHAR2(3 BYTE),
    "TAX_RECOVER_DIV"     VARCHAR2(2 BYTE),
    "TAX_NO_OF_YR"        NUMBER(2, 0),
    "TAX_START_DATE"      DATE,
    "APPROVAL_FLAG"       VARCHAR2(1 BYTE),
    "MTAX_FLAG"           VARCHAR2(1 BYTE),
    CONSTRAINT NLCTL_COMPANY_FK FOREIGN KEY ("COMPANY_CODE", "PLANT_NO")
        REFERENCES COMPANY ("COMPANY_CODE", "PLANT_NO") ENABLE
);

CREATE UNIQUE INDEX NLCTL_UK ON NLCTL ("COMPANY_CODE", "PLANT_NO");

ALTER TABLE NLCTL
    ADD CONSTRAINT NLCTL_UK UNIQUE ("COMPANY_CODE", "PLANT_NO")
        USING INDEX NLCTL_UK ENABLE;

COMMENT ON COLUMN NLCTL."ASSET_FR" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."ASSET_TO" IS 'ACCOUNT TO';
COMMENT ON COLUMN NLCTL."LIABILITY_FR" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."LIABILITY_TO" IS 'ACCOUNT TO';
COMMENT ON COLUMN NLCTL."REVENUE_FR" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."REVENUE_TO" IS 'ACCOUNT TO';
COMMENT ON COLUMN NLCTL."EXPENSE_FR" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."EXPENSE_TO" IS 'ACCOUNT TO';
COMMENT ON COLUMN NLCTL."MFG_EXPENSE_FR" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."MFG_EXPENSE_TO" IS 'ACCOUNT TO';
COMMENT ON COLUMN NLCTL."ADM_EXPENSE_FR" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."ADM_EXPENSE_TO" IS 'ACCOUNT TO';
COMMENT ON COLUMN NLCTL."CAPITAL_FR" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."CAPITAL_TO" IS 'ACCOUNT TO';
COMMENT ON COLUMN NLCTL."CURRENT_PROFIT_LOSS" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."GROSS_PROFIT" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."NET_PROFIT_LOSS" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."GST_O_STD_ACCT_CODE" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."GST_O_ZRO_ACCT_CODE" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."GST_O_STD_MEMO_CODE" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."GST_O_ZRO_MEMO_CODE" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."GST_O_EXM_MEMO_CODE" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."GST_O_OUT_MEMO_CODE" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."GST_I_STD_ACCT_CODE" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."GST_I_ZRO_ACCT_CODE" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."GST_I_STD_MEMO_CODE" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."GST_I_ZRO_MEMO_CODE" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."GST_I_EXM_MEMO_CODE" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."GST_I_OUT_MEMO_CODE" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."STOCK_ACCT_CODE" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."WIP_ACCT_CODE" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."ACCRUED_ACCT_CODE" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."OTHER_INCOME_FR" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."OTHER_INCOME_TO" IS 'ACCOUNT TO';
COMMENT ON COLUMN NLCTL."RECOVERY_FR" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."RECOVERY_TO" IS 'ACCOUNT TO';
COMMENT ON COLUMN NLCTL."TAXATION_FR" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."TAXATION_TO" IS 'ACCOUNT TO';
COMMENT ON COLUMN NLCTL."GST_ACCT_CODE" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."INPUT_TAX_FR" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."INPUT_TAX_TO" IS 'ACCOUNT TO';
COMMENT ON COLUMN NLCTL."OUTPUT_TAX_FR" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."OUTPUT_TAX_TO" IS 'ACCOUNT TO';
COMMENT ON COLUMN NLCTL."BILL_RECEIVABLE_FR" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."BILL_RECEIVABLE_TO" IS 'ACCOUNT TO';
COMMENT ON COLUMN NLCTL."ACCRUED_SALES_ACCT" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."ST_HP_INT_ACCT" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."LT_HP_INT_ACCT" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."TAX_WITHHOLD_ACCT" IS 'ACCOUNT FROM';
COMMENT ON COLUMN NLCTL."TAX_RECOVER_ACCT" IS 'ACCOUNT FROM';
COMMENT ON TABLE NLCTL IS 'General Ledger Control';

GRANT ALTER ON NLCTL TO PUBLIC WITH GRANT OPTION;
GRANT DELETE ON NLCTL TO PUBLIC WITH GRANT OPTION;
GRANT INDEX ON NLCTL TO PUBLIC WITH GRANT OPTION;
GRANT INSERT ON NLCTL TO PUBLIC WITH GRANT OPTION;
GRANT SELECT ON NLCTL TO PUBLIC WITH GRANT OPTION;
GRANT UPDATE ON NLCTL TO PUBLIC WITH GRANT OPTION;
GRANT REFERENCES ON NLCTL TO PUBLIC WITH GRANT OPTION;

----------------------------------------------- INSERT INTO COMPANY AND NLCTL -----------------------------------------------
INSERT INTO COMPANY (COMPANY_CODE, PLANT_NO, COMPANY_NAME, PLANT_NAME, NAME_SHORT, ADDRESS1, ADDRESS2, ADDRESS3, ADDRESS4, PCODE, TEL_NO, TEL_NO2, FAX_NO, FAX_NO2, CURRENCY_CODE, BUSINESS_NATURE, COUNTRY_CODE, COUNTRY_NAME, REGION_CODE, REGION_NAME, STATE_CODE, STATE_NAME, STOCK_LOC, DATE_FORMAT, ACCESS_IN, ACCESS_BOM, ACCESS_MRP, ACCESS_WC, ACCESS_CRP, ACCESS_MPS, ACCESS_SFC, ACCESS_CA, ACCESS_SOP, ACCESS_PUR, ACCESS_NL, ACCESS_SL, ACCESS_PL, ACCESS_PR, ACCESS_CAD, ACCESS_ST, ACCESS_LOT, ACCESS_EX, ACCESS_FA, ACCESS_PER, ACCESS_UTIL, TRADER_CODE, TAX_REGN_NO, FREIGHT_PERCENT, HANDLING_PERCENT, INVOICE_TITLE, PASSWORD_CHANGE, BUSINESS_REGN_NO, ACCESS_CP, TAX_CAT, PRODUCT_VERSION, GAF_VERSION, CURRENCY_DECIMAL, TZNAME, SYSTEM_EMAIL) VALUES ('050', 0, 'KES SYSTEMS, INC.', 'TEMPE', 'KESI_TEMPE', '1407 W. DRIVERS WAY', 'TEMPE, AZ', null, null, '85284', '(480) 747-9239', null, '(480) 747-9210', null, 'USD', 'Financial', 'USA', 'UNITED STATES OF AMERICA', null, null, null, null, 'TE', '02', '1', '1', '0', '0', '0', '0', '0', '1', '1', '1', '1', '1', '1', '0', '0', '0', '0', '0', '1', '0', '0', null, '52-1537846', 0.0000, 0.0000, null, 999, null, '1', 'VAT', null, null, 4, 'US/Pacific', null);
INSERT INTO COMPANY (COMPANY_CODE, PLANT_NO, COMPANY_NAME, PLANT_NAME, NAME_SHORT, ADDRESS1, ADDRESS2, ADDRESS3, ADDRESS4, PCODE, TEL_NO, TEL_NO2, FAX_NO, FAX_NO2, CURRENCY_CODE, BUSINESS_NATURE, COUNTRY_CODE, COUNTRY_NAME, REGION_CODE, REGION_NAME, STATE_CODE, STATE_NAME, STOCK_LOC, DATE_FORMAT, ACCESS_IN, ACCESS_BOM, ACCESS_MRP, ACCESS_WC, ACCESS_CRP, ACCESS_MPS, ACCESS_SFC, ACCESS_CA, ACCESS_SOP, ACCESS_PUR, ACCESS_NL, ACCESS_SL, ACCESS_PL, ACCESS_PR, ACCESS_CAD, ACCESS_ST, ACCESS_LOT, ACCESS_EX, ACCESS_FA, ACCESS_PER, ACCESS_UTIL, TRADER_CODE, TAX_REGN_NO, FREIGHT_PERCENT, HANDLING_PERCENT, INVOICE_TITLE, PASSWORD_CHANGE, BUSINESS_REGN_NO, ACCESS_CP, TAX_CAT, PRODUCT_VERSION, GAF_VERSION, CURRENCY_DECIMAL, TZNAME, SYSTEM_EMAIL) VALUES ('050', 1, 'KES SYSTEMS, INC.', 'DALLAS', 'KESI_DALL', '1407 W. DRIVERS WAY', 'TEMPE, AZ', null, null, '85284', '(480) 747-9239', null, '(480) 747-9210', null, 'USD', 'Financial', 'USA', 'UNITED STATES OF AMERICA', null, null, null, null, 'DS', '02', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '1', '0', '0', '0', '0', '0', '1', '0', '0', null, null, 0.0000, 0.0000, null, 999, null, '1', 'VAT', null, null, 4, 'US/Central', null);

INSERT INTO NLCTL (COMPANY_CODE, PLANT_NO, START_PERIOD, START_MONTH, START_YEAR, CURRENT_FIN_MONTH, CURRENT_FIN_YEAR, ASSET_FR, ASSET_TO, LIABILITY_FR, LIABILITY_TO, REVENUE_FR, REVENUE_TO, EXPENSE_FR, EXPENSE_TO, MFG_EXPENSE_FR, MFG_EXPENSE_TO, ADM_EXPENSE_FR, ADM_EXPENSE_TO, CAPITAL_FR, CAPITAL_TO, CURRENT_PROFIT_LOSS, GROSS_PROFIT, NET_PROFIT_LOSS, USER1, BATCH_NO1, TRAN_NO1, USER2, BATCH_NO2, TRAN_NO2, USER3, BATCH_NO3, TRAN_NO3, USER4, BATCH_NO4, TRAN_NO4, USER5, BATCH_NO5, TRAN_NO5, USER6, BATCH_NO6, TRAN_NO6, USER7, BATCH_NO7, TRAN_NO7, USER8, BATCH_NO8, TRAN_NO8, USER9, BATCH_NO9, TRAN_NO9, USER10, BATCH_NO10, TRAN_NO10, EOP_FLAG, EOY_FLAG, GST_START_DATE, GST_STD_PCT, GST_ZRO_PCT, GST_O_STD_ACCT_CODE, GST_O_ZRO_ACCT_CODE, GST_O_STD_MEMO_CODE, GST_O_ZRO_MEMO_CODE, GST_O_EXM_MEMO_CODE, GST_O_OUT_MEMO_CODE, GST_I_STD_ACCT_CODE, GST_I_ZRO_ACCT_CODE, GST_I_STD_MEMO_CODE, GST_I_ZRO_MEMO_CODE, GST_I_EXM_MEMO_CODE, GST_I_OUT_MEMO_CODE, STOCK_ACCT_CODE, STOCK_DEPT_CODE, STOCK_DIV_CODE, WIP_ACCT_CODE, WIP_DEPT_CODE, WIP_DIV_CODE, ACCRUED_ACCT_CODE, ACCRUED_DEPT_CODE, ACCRUED_DIV_CODE, INVENTORY_ENABLED, INVENTORY_MONTH, INVENTORY_YEAR, OTHER_INCOME_FR, OTHER_INCOME_TO, RECOVERY_FR, RECOVERY_TO, TAXATION_FR, TAXATION_TO, COUNT_ENABLED, GST_ACCT_CODE, INPUT_TAX_FR, INPUT_TAX_TO, OUTPUT_TAX_FR, OUTPUT_TAX_TO, BILL_RECEIVABLE_FR, BILL_RECEIVABLE_TO, ACCRUED_SALES_ACCT, ACCRUED_SALES_DEPT, ACCRUED_SALES_DIV, ST_HP_INT_ACCT, ST_HP_INT_DEPT, ST_HP_INT_DIV, LT_HP_INT_ACCT, LT_HP_INT_DEPT, LT_HP_INT_DIV, TAX_WITHHOLD_ACCT, TAX_WITHHOLD_DEPT, TAX_WITHHOLD_DIV, TAX_RECOVER_ACCT, TAX_RECOVER_DEPT, TAX_RECOVER_DIV, TAX_NO_OF_YR, TAX_START_DATE, APPROVAL_FLAG, MTAX_FLAG) VALUES ('050', 0, TO_DATE('2021-08-01', 'YYYY-MM-DD HH24:MI:SS'), 8, 2021, 11, 2021, '010000', '099999', '100000', '199999', '300000', '319999', '330000', '799999', '330000', '499999', '500000', '799999', '200000', '299999', '240120', '240100', '679998', 'NATASCHA', 1, 0, 'KESI.TEMP', 2, 0, 'LEHHO', 3, 0, 'OLIVIA', 4, 17, null, 5, 0, 'ADMIN', 6, 0, 'LAURA', 7, 0, 'SHELLY', 8, 0, 'SYLVIA', 9, 0, 'SU-CHUAN', 10, 0, null, null, TO_DATE('1994-04-01', 'YYYY-MM-DD HH24:MI:SS'), 1.00, 0.00, '110331', null, '110335', '110337', '110336', null, '051500', null, '051504', '051506', '051505', null, '050300', '000', '00', null, null, null, '110120', '000', '00', 'Y', 11, 2021, '600000', '699999', '597100', '597100', '700000', '799999', null, null, '051500', '051900', '110331', '110700', '051300', '051400', '051150', '000', '00', '054210', '000', '00', '054215', '000', '00', '140210', '000', '00', '140220', '000', '00', 3, TO_DATE('2013-08-01', 'YYYY-MM-DD HH24:MI:SS'), 'Y', 'N');
INSERT INTO NLCTL (COMPANY_CODE, PLANT_NO, START_PERIOD, START_MONTH, START_YEAR, CURRENT_FIN_MONTH, CURRENT_FIN_YEAR, ASSET_FR, ASSET_TO, LIABILITY_FR, LIABILITY_TO, REVENUE_FR, REVENUE_TO, EXPENSE_FR, EXPENSE_TO, MFG_EXPENSE_FR, MFG_EXPENSE_TO, ADM_EXPENSE_FR, ADM_EXPENSE_TO, CAPITAL_FR, CAPITAL_TO, CURRENT_PROFIT_LOSS, GROSS_PROFIT, NET_PROFIT_LOSS, USER1, BATCH_NO1, TRAN_NO1, USER2, BATCH_NO2, TRAN_NO2, USER3, BATCH_NO3, TRAN_NO3, USER4, BATCH_NO4, TRAN_NO4, USER5, BATCH_NO5, TRAN_NO5, USER6, BATCH_NO6, TRAN_NO6, USER7, BATCH_NO7, TRAN_NO7, USER8, BATCH_NO8, TRAN_NO8, USER9, BATCH_NO9, TRAN_NO9, USER10, BATCH_NO10, TRAN_NO10, EOP_FLAG, EOY_FLAG, GST_START_DATE, GST_STD_PCT, GST_ZRO_PCT, GST_O_STD_ACCT_CODE, GST_O_ZRO_ACCT_CODE, GST_O_STD_MEMO_CODE, GST_O_ZRO_MEMO_CODE, GST_O_EXM_MEMO_CODE, GST_O_OUT_MEMO_CODE, GST_I_STD_ACCT_CODE, GST_I_ZRO_ACCT_CODE, GST_I_STD_MEMO_CODE, GST_I_ZRO_MEMO_CODE, GST_I_EXM_MEMO_CODE, GST_I_OUT_MEMO_CODE, STOCK_ACCT_CODE, STOCK_DEPT_CODE, STOCK_DIV_CODE, WIP_ACCT_CODE, WIP_DEPT_CODE, WIP_DIV_CODE, ACCRUED_ACCT_CODE, ACCRUED_DEPT_CODE, ACCRUED_DIV_CODE, INVENTORY_ENABLED, INVENTORY_MONTH, INVENTORY_YEAR, OTHER_INCOME_FR, OTHER_INCOME_TO, RECOVERY_FR, RECOVERY_TO, TAXATION_FR, TAXATION_TO, COUNT_ENABLED, GST_ACCT_CODE, INPUT_TAX_FR, INPUT_TAX_TO, OUTPUT_TAX_FR, OUTPUT_TAX_TO, BILL_RECEIVABLE_FR, BILL_RECEIVABLE_TO, ACCRUED_SALES_ACCT, ACCRUED_SALES_DEPT, ACCRUED_SALES_DIV, ST_HP_INT_ACCT, ST_HP_INT_DEPT, ST_HP_INT_DIV, LT_HP_INT_ACCT, LT_HP_INT_DEPT, LT_HP_INT_DIV, TAX_WITHHOLD_ACCT, TAX_WITHHOLD_DEPT, TAX_WITHHOLD_DIV, TAX_RECOVER_ACCT, TAX_RECOVER_DEPT, TAX_RECOVER_DIV, TAX_NO_OF_YR, TAX_START_DATE, APPROVAL_FLAG, MTAX_FLAG) VALUES ('050', 1, TO_DATE('2021-08-01', 'YYYY-MM-DD HH24:MI:SS'), 8, 2021, 11, 2021, '010000', '099999', '100000', '199999', '300000', '319999', '330000', '799999', '330000', '499999', '500000', '799999', '200000', '299999', '240120', '240100', '679998', 'NATASCHA01', 1, 0, 'KESI01.TEMP', 2, 50, 'LEHHO01', 3, 0, 'OLIVIA01', 4, 14, null, 5, 0, 'ADMIN01', 6, 0, 'LAURA01', 7, 0, null, 8, 0, 'SYLVIA01', 9, 0, 'SU-CHUAN01', 10, 0, null, null, TO_DATE('1994-04-01', 'YYYY-MM-DD HH24:MI:SS'), 1.00, 0.00, '110331', null, '110335', '110337', '110336', null, '051500', null, '051504', '051506', '051505', null, '050300', '000', '00', null, null, null, '110120', '000', '00', 'Y', 6, 2018, '600000', '699999', '597100', '597100', '700000', '799999', null, null, '051500', '051900', '110331', '110700', '051300', '051400', '051150', '000', '00', '054210', '000', '00', '054215', '000', '00', '140210', '000', '00', '140220', '000', '00', 3, TO_DATE('2013-08-01', 'YYYY-MM-DD HH24:MI:SS'), 'Y', 'N');


