----------------------------------------------- COQ -----------------------------------------------

CREATE TABLE COQ
(
    "COMPANY_CODE"   VARCHAR2(3 BYTE)  NOT NULL ENABLE,
    "PLANT_NO"       NUMBER(3, 0)      NOT NULL ENABLE,
    "DOCM_NO"        VARCHAR2(15 BYTE) NOT NULL ENABLE,
    "DOCM_TYPE"      VARCHAR2(3 BYTE),
    "CAT_CODE"       VARCHAR2(3 BYTE),
    "REQUESTOR"      VARCHAR2(30 BYTE),
    "PROJECT_NO_SUB" VARCHAR2(15 BYTE),
    "SRA_NO"         VARCHAR2(15 BYTE),
    "STATUS"         VARCHAR2(1 BYTE),
    "ENTRY_USER"     VARCHAR2(30 BYTE),
    "ENTRY_DATE"     DATE,
    "REMARKS"        VARCHAR2(2000 BYTE)
);

CREATE UNIQUE INDEX COQ_PK ON COQ ("COMPANY_CODE", "PLANT_NO", "DOCM_NO");

ALTER TABLE COQ
    ADD CONSTRAINT COQ_PK PRIMARY KEY ("COMPANY_CODE", "PLANT_NO", "DOCM_NO")
        USING INDEX COQ_PK ENABLE;

----------------------------------------------- COQ_DET -----------------------------------------------

CREATE TABLE COQ_DET
(
    "COMPANY_CODE" VARCHAR2(3 BYTE)  NOT NULL ENABLE,
    "PLANT_NO"     NUMBER(3, 0)      NOT NULL ENABLE,
    "DOCM_NO"      VARCHAR2(15 BYTE) NOT NULL ENABLE,
    "REC_SEQ"      NUMBER(3, 0)      NOT NULL ENABLE,
    "SEQ_NO"       NUMBER(3, 0),
    "ITEM_TYPE"    NUMBER(2, 0),
    "PART_NO"      VARCHAR2(60 BYTE),
    "ITEM_NO"      VARCHAR2(15 BYTE),
    "ASSEMBLY_NO"  VARCHAR2(15 BYTE),
    "DESCRIPTION"  VARCHAR2(1000 BYTE),
    "DOCM_QTY"     NUMBER(16, 4),
    "REASON_CODE"  VARCHAR2(5 BYTE),
    "REASON_DESC"  VARCHAR2(60 BYTE),
    "DIV_CODE"     VARCHAR2(2 BYTE),
    "DEPT_CODE"    VARCHAR2(3 BYTE),
    CONSTRAINT COQ_DET_FK FOREIGN KEY ("COMPANY_CODE", "PLANT_NO", "DOCM_NO")
        REFERENCES COQ ("COMPANY_CODE", "PLANT_NO", "DOCM_NO") ENABLE
);

CREATE UNIQUE INDEX COQ_DET_PK ON COQ_DET ("COMPANY_CODE", "PLANT_NO", "DOCM_NO", "REC_SEQ");

ALTER TABLE COQ_DET
    ADD CONSTRAINT COQ_DET_PK PRIMARY KEY ("COMPANY_CODE", "PLANT_NO", "DOCM_NO", "REC_SEQ")
        USING INDEX COQ_DET_PK ENABLE;

----------------------------------------------- COQ_DET_SUB -----------------------------------------------

CREATE TABLE COQ_DET_SUB
(
    "COMPANY_CODE" VARCHAR2(3 BYTE)  NOT NULL ENABLE,
    "PLANT_NO"     NUMBER(3, 0)      NOT NULL ENABLE,
    "DOCM_NO"      VARCHAR2(15 BYTE) NOT NULL ENABLE,
    "DET_REC_SEQ"  NUMBER(3, 0)      NOT NULL ENABLE,
    "SEQ_NO"       NUMBER(3, 0)      NOT NULL ENABLE,
    "SIV_NO"       VARCHAR2(15 BYTE),
    "QTY"          NUMBER(16, 4),
    "PO_NO"        VARCHAR2(15 BYTE),
    "UNIT_PRICE"   NUMBER(16, 4),
    "ENTRY_DATE"   DATE,
    CONSTRAINT COQ_DET_SUB_FK FOREIGN KEY ("COMPANY_CODE", "PLANT_NO", "DOCM_NO", "DET_REC_SEQ")
        REFERENCES COQ_DET ("COMPANY_CODE", "PLANT_NO", "DOCM_NO", "REC_SEQ") ENABLE
);

CREATE UNIQUE INDEX COQ_DET_SUB_PK ON COQ_DET_SUB ("COMPANY_CODE", "PLANT_NO", "DOCM_NO", "DET_REC_SEQ", "SEQ_NO");

ALTER TABLE COQ_DET_SUB
    ADD CONSTRAINT COQ_DET_SUB_PK PRIMARY KEY ("COMPANY_CODE", "PLANT_NO", "DOCM_NO", "DET_REC_SEQ", "SEQ_NO")
        USING INDEX COQ_DET_SUB_PK ENABLE;

----------------------------------------------- COQ_REASONS -----------------------------------------------

CREATE TABLE COQ_REASONS
(
    "COMPANY_CODE" VARCHAR2(3 BYTE)  NOT NULL ENABLE,
    "PLANT_NO"     NUMBER(3, 0)      NOT NULL ENABLE,
    "DOCM_TYPE"    VARCHAR2(3 BYTE)  NOT NULL ENABLE,
    "DOCM_DESC"    VARCHAR2(60 BYTE) NOT NULL ENABLE,
    "CAT_CODE"     VARCHAR2(3 BYTE)  NOT NULL ENABLE,
    "CAT_DESC"     VARCHAR2(60 BYTE) NOT NULL ENABLE
);

CREATE UNIQUE INDEX COQ_REASONS_PK ON COQ_REASONS ("COMPANY_CODE", "PLANT_NO", "DOCM_TYPE", "CAT_CODE");

ALTER TABLE COQ_REASONS
    ADD CONSTRAINT COQ_REASONS_PK PRIMARY KEY ("COMPANY_CODE", "PLANT_NO", "DOCM_TYPE", "CAT_CODE")
        USING INDEX COQ_REASONS_PK ENABLE;

----------------------------------------------- COQ_REASONS_DET -----------------------------------------------

CREATE TABLE COQ_REASONS_DET
(
    "COMPANY_CODE" VARCHAR2(3 BYTE) NOT NULL ENABLE,
    "PLANT_NO"     NUMBER(3, 0)     NOT NULL ENABLE,
    "DOCM_TYPE"    VARCHAR2(3 BYTE) NOT NULL ENABLE,
    "CAT_CODE"     VARCHAR2(3 BYTE) NOT NULL ENABLE,
    "REASON_CODE"  VARCHAR2(3 BYTE) NOT NULL ENABLE,
    "REASON_DESC"  VARCHAR2(60 BYTE),
    "STATUS"       VARCHAR2(1 BYTE),
    "ENTRY_USER"   VARCHAR2(30 BYTE),
    "ENTRY_DATE"   DATE,
    CONSTRAINT COQ_REASONS_DET_FK FOREIGN KEY ("COMPANY_CODE", "PLANT_NO", "DOCM_TYPE", "CAT_CODE")
        REFERENCES COQ_REASONS ("COMPANY_CODE", "PLANT_NO", "DOCM_TYPE", "CAT_CODE") ENABLE
);

CREATE UNIQUE INDEX COQ_REASONS_DET_PK ON COQ_REASONS_DET ("COMPANY_CODE", "PLANT_NO", "DOCM_TYPE", "CAT_CODE", "REASON_CODE");

ALTER TABLE COQ_REASONS_DET
    ADD CONSTRAINT COQ_REASONS_DET_PK PRIMARY KEY ("COMPANY_CODE", "PLANT_NO", "DOCM_TYPE", "CAT_CODE", "REASON_CODE")
        USING INDEX COQ_REASONS_DET_PK ENABLE;

