------------ ITEM table creation ------------------
CREATE TABLE ITEM
(	"COMPANY_CODE" VARCHAR2(3 BYTE) NOT NULL ENABLE,
     "PLANT_NO" NUMBER(3,0) NOT NULL ENABLE,
     "ITEM_NO" VARCHAR2(15 BYTE) NOT NULL ENABLE,
     "VERSION" NUMBER NOT NULL,
     "LOC" VARCHAR2(5 BYTE) NOT NULL ENABLE,
     "PART_NO" VARCHAR2(60 BYTE),
     "DESCRIPTION" VARCHAR2(1000 BYTE),
     "CATEGORY_CODE" VARCHAR2(10 BYTE),
     "CATEGORY_SUB_CODE" VARCHAR2(10 BYTE),
     "CATEGORY_GROUP" VARCHAR2(2 BYTE),
     "MANUFACTURER" VARCHAR2(30 BYTE),
     "UOM" VARCHAR2(3 BYTE),
     "DRAWING" VARCHAR2(10 BYTE),
     "ISSUE_NO" VARCHAR2(30 BYTE),
     "SPEC_NO" VARCHAR2(30 BYTE),
     "QA" VARCHAR2(10 BYTE),
     "REV" VARCHAR2(3 BYTE),
     "CLASS" VARCHAR2(3 BYTE),
     "SOURCE" VARCHAR2(1 BYTE),
     "ORDER_POLICY" VARCHAR2(3 BYTE),
     "ALTERNATE" VARCHAR2(15 BYTE),
     "PRODUCT_GROUP" VARCHAR2(10 BYTE),
     "BUYER" VARCHAR2(20 BYTE),
     "SUPPLIER_CODE" VARCHAR2(10 BYTE),
     "ACCOUNT_CODE" VARCHAR2(10 BYTE),
     "COUNT_CODE" VARCHAR2(1 BYTE),
     "DIV_CODE" VARCHAR2(2 BYTE),
     "DEPT_CODE" VARCHAR2(3 BYTE),
     "REMARKS" VARCHAR2(2000 BYTE),
     "QOH" NUMBER(16,4),
     "BALBF_QTY" NUMBER(16,4),
     "LAST_BALBF_QTY" NUMBER(16,4),
     "PRICEA" NUMBER(16,4),
     "PRICEB" NUMBER(16,4),
     "PRICEC" NUMBER(16,4),
     "REORDER" NUMBER(16,4),
     "LEADTIME" NUMBER(3,0),
     "LOT" NUMBER(16,4),
     "YTD_PURCH" NUMBER(16,4),
     "YTD_PROD" NUMBER(16,4),
     "YTD_SALE" NUMBER(16,4),
     "YTD_ISSUE" NUMBER(16,4),
     "YTD_RECEIPT" NUMBER(16,4),
     "OBSOLETE_CODE" VARCHAR2(1 BYTE),
     "OBSOLETE_QTY" NUMBER(16,4),
     "BATCH_NO" NUMBER(8,0),
     "ORDER_QTY" NUMBER(16,4),
     "PICKED_QTY" NUMBER(16,4),
     "PRODN_RESV" NUMBER(16,4),
     "SALES_RESV" NUMBER(16,4),
     "ADV_PR_RESV" NUMBER(16,4),
     "SAFETY_STOCK" NUMBER(16,4),
     "STD_SETUP" NUMBER(16,4),
     "STD_MATERIAL" NUMBER(16,4),
     "STD_LABOR" NUMBER(16,4),
     "STD_BURDEN" NUMBER(16,4),
     "STD_SUBCONTRACT" NUMBER(16,4),
     "STD_MACHINE" NUMBER(16,4),
     "FREIGHT" NUMBER(16,4),
     "HANDLING" NUMBER(16,4),
     "CUSTOM_DUTY" NUMBER(16,4),
     "LAST_PUR_PRICE" NUMBER(16,4),
     "LAST_PUR_DATE" DATE,
     "LAST_TRAN_DATE" DATE,
     "LAST_COUNT_DATE" DATE,
     "COST_VARIANCE" NUMBER(16,4),
     "QC_FLAG" VARCHAR2(1 BYTE),
     "COUNT_QOH" NUMBER(16,4),
     "COUNT_TAG" VARCHAR2(10 BYTE),
     "COUNT_UPD_IND" VARCHAR2(1 BYTE),
     "DIMENSION" VARCHAR2(60 BYTE),
     "ROHS_STATUS" VARCHAR2(1 BYTE),
     "RPC_RESV" NUMBER(16,4),
     "MRV_RESV" NUMBER(16,4),
     "MSL_CODE" VARCHAR2(3 BYTE),
     "OPEN_CLOSE" VARCHAR2(1 BYTE),
     "CLOSE_DATE" DATE,
     "OBSOLETE_ITEM" VARCHAR2(15 BYTE),
     "OBSOLETE_DATE" DATE,
     "REF_URL" VARCHAR2(200 BYTE),
     "REQUESTOR" VARCHAR2(30 BYTE),
     "STORAGE_SHELF" VARCHAR2(15 BYTE),
     "LAST_MODIFIED_DATE" DATE,
     "ENTRY_USER" VARCHAR2(30 BYTE),
     "ENTRY_DATE" DATE
);

CREATE UNIQUE INDEX ITEM_PK ON ITEM ("COMPANY_CODE", "PLANT_NO", "ITEM_NO");

ALTER TABLE ITEM ADD CONSTRAINT ITEM_PK PRIMARY KEY ("COMPANY_CODE", "PLANT_NO", "ITEM_NO")
    USING INDEX ITEM_PK ENABLE;

CREATE INDEX ITEMLOC_IDX2 ON ITEM ("COMPANY_CODE", "PLANT_NO", "ITEM_NO", "LOC");

CREATE INDEX ITEM_IDX ON ITEM ("PART_NO");

------------ ITEMLOC table creation ------------------

CREATE TABLE ITEMLOC
(	"COMPANY_CODE" VARCHAR2(3 BYTE) NOT NULL ENABLE,
     "PLANT_NO" NUMBER(3,0) NOT NULL ENABLE,
     "ITEM_NO" VARCHAR2(15 BYTE) NOT NULL ENABLE,
     "LOC" VARCHAR2(5 BYTE) NOT NULL ENABLE,
     "VERSION" NUMBER NOT NULL,
     "PART_NO" VARCHAR2(60 BYTE),
     "DESCRIPTION" VARCHAR2(1000 BYTE),
     "CATEGORY_CODE" VARCHAR2(10 BYTE),
     "CATEGORY_SUB_CODE" VARCHAR2(10 BYTE),
     "DIV_CODE" VARCHAR2(2 BYTE),
     "DEPT_CODE" VARCHAR2(3 BYTE),
     "QOH" NUMBER(16,4),
     "BALBF_QTY" NUMBER(16,4),
     "LAST_BALBF_QTY" NUMBER(16,4),
     "YTD_PURCH" NUMBER(16,4),
     "YTD_PROD" NUMBER(16,4),
     "YTD_SALE" NUMBER(16,4),
     "YTD_ISSUE" NUMBER(16,4),
     "YTD_RECEIPT" NUMBER(16,4),
     "BATCH_NO" NUMBER(8,0),
     "ORDER_QTY" NUMBER(16,4),
     "PICKED_QTY" NUMBER(16,4),
     "PRODN_RESV" NUMBER(16,4),
     "SALES_RESV" NUMBER(16,4),
     "ADV_PR_RESV" NUMBER(16,4),
     "STD_SETUP" NUMBER(16,4),
     "STD_MATERIAL" NUMBER(16,4),
     "STD_LABOR" NUMBER(16,4),
     "STD_BURDEN" NUMBER(16,4),
     "STD_SUBCONTRACT" NUMBER(16,4),
     "STD_MACHINE" NUMBER(16,4),
     "FREIGHT" NUMBER(16,4),
     "HANDLING" NUMBER(16,4),
     "CUSTOM_DUTY" NUMBER(16,4),
     "LAST_PUR_PRICE" NUMBER(16,4),
     "LAST_PUR_DATE" DATE,
     "LAST_TRAN_DATE" DATE,
     "COST_VARIANCE" NUMBER(16,4),
     "BIN" VARCHAR2(8 BYTE),
     "LAST_COUNT_DATE" DATE,
     "COUNT_QOH" NUMBER(16,4),
     "COUNT_TAG" VARCHAR2(10 BYTE),
     "COUNT_UPD_IND" VARCHAR2(1 BYTE),
     "RPC_RESV" NUMBER(16,4),
     "MRV_RESV" NUMBER(16,4),
     CONSTRAINT "ITEMLOC_FK" FOREIGN KEY ("COMPANY_CODE", "PLANT_NO", "ITEM_NO")
         REFERENCES ITEM ("COMPANY_CODE", "PLANT_NO", "ITEM_NO") ENABLE
);

CREATE UNIQUE INDEX ITEMLOC_PK ON ITEMLOC ("COMPANY_CODE", "PLANT_NO", "ITEM_NO", "LOC");

ALTER TABLE ITEMLOC ADD CONSTRAINT "ITEMLOC_PK" PRIMARY KEY ("COMPANY_CODE", "PLANT_NO", "ITEM_NO", "LOC")
    USING INDEX ITEMLOC_PK ENABLE;

CREATE INDEX ITEMLOC_IDX ON ITEMLOC ("PART_NO", "LOC");

------------ ITEMBATC table creation ------------------

CREATE TABLE ITEMBATC
(	"COMPANY_CODE" VARCHAR2(3 BYTE) NOT NULL ENABLE,
     "PLANT_NO" NUMBER(3,0) NOT NULL ENABLE,
     "ITEM_NO" VARCHAR2(15 BYTE) NOT NULL ENABLE,
     "LOC" VARCHAR2(5 BYTE) NOT NULL ENABLE,
     "BATCH_NO" NUMBER(8,0) NOT NULL ENABLE,
     "VERSION" NUMBER NOT NULL,
     "TRAN_DATE" DATE,
     "DATE_CODE" NUMBER(4,0),
     "PO_NO" VARCHAR2(15 BYTE),
     "PO_REC_SEQ" NUMBER(3,0),
     "GRN_NO" VARCHAR2(15 BYTE),
     "GRN_SEQ" NUMBER(3,0),
     "QOH" NUMBER(16,4),
     "ORI_QOH" NUMBER(16,4),
     "STD_SETUP" NUMBER(16,4),
     "STD_MATERIAL" NUMBER(16,4),
     "STD_LABOR" NUMBER(16,4),
     "STD_BURDEN" NUMBER(16,4),
     "STD_SUBCONTRACT" NUMBER(16,4),
     "STD_MACHINE" NUMBER(16,4),
     CONSTRAINT "ITEMBATC_FK" FOREIGN KEY ("COMPANY_CODE", "PLANT_NO", "ITEM_NO", "LOC")
         REFERENCES ITEMLOC ("COMPANY_CODE", "PLANT_NO", "ITEM_NO", "LOC") ENABLE
);

CREATE UNIQUE INDEX ITEMBATC_PK ON ITEMBATC ("COMPANY_CODE", "PLANT_NO", "ITEM_NO", "LOC", "BATCH_NO");

ALTER TABLE ITEMBATC ADD CONSTRAINT ITEMBATC_PK PRIMARY KEY ("COMPANY_CODE", "PLANT_NO", "ITEM_NO", "LOC", "BATCH_NO")
    USING INDEX ITEMBATC_PK ENABLE;

------------ INHIST table creation ------------------

CREATE TABLE INHIST
(	"COMPANY_CODE" VARCHAR2(3 BYTE) NOT NULL ENABLE,
     "PLANT_NO" NUMBER(3,0) NOT NULL ENABLE,
     "ITEM_NO" VARCHAR2(15 BYTE) NOT NULL ENABLE,
     "LOC" VARCHAR2(5 BYTE) NOT NULL ENABLE,
     "TRAN_DATE" DATE NOT NULL ENABLE,
     "TRAN_TIME" VARCHAR2(10 BYTE) NOT NULL ENABLE,
     "TRAN_TYPE" VARCHAR2(5 BYTE) NOT NULL ENABLE,
     "DOCM_NO" VARCHAR2(15 BYTE) NOT NULL ENABLE,
     "VERSION" NUMBER NOT NULL,
     "IN_QTY" NUMBER(16,4),
     "OUT_QTY" NUMBER(16,4),
     "ACTUAL_COST" NUMBER(16,4),
     "PROJECT_NO" VARCHAR2(15 BYTE),
     "PR_NO" VARCHAR2(15 BYTE),
     "PO_NO" VARCHAR2(15 BYTE),
     "DO_NO" VARCHAR2(15 BYTE),
     "GRN_NO" VARCHAR2(15 BYTE),
     "REMARKS" VARCHAR2(30 BYTE),
     CONSTRAINT "INHIST_FK" FOREIGN KEY ("COMPANY_CODE", "PLANT_NO", "ITEM_NO", "LOC")
         REFERENCES ITEMLOC ("COMPANY_CODE", "PLANT_NO", "ITEM_NO", "LOC") ENABLE
);

CREATE INDEX INHIST_IDX1 ON INHIST ("ITEM_NO");


------------ INAUDIT table creation ------------------

CREATE TABLE INAUDIT
(	"COMPANY_CODE" VARCHAR2(3 BYTE) NOT NULL ENABLE,
     "PLANT_NO" NUMBER(3,0) NOT NULL ENABLE,
     "ITEM_NO" VARCHAR2(15 BYTE) NOT NULL ENABLE,
     "LOC" VARCHAR2(5 BYTE) NOT NULL ENABLE,
     "TRAN_DATE" DATE NOT NULL ENABLE,
     "TRAN_TIME" VARCHAR2(10 BYTE) NOT NULL ENABLE,
     "VERSION" NUMBER NOT NULL,
     "TRAN_TYPE" VARCHAR2(5 BYTE),
     "DOCM_NO" VARCHAR2(15 BYTE),
     "UOM" VARCHAR2(3 BYTE),
     "DOCM_DATE" DATE,
     "DIV_CODE" VARCHAR2(2 BYTE),
     "DEPT_CODE" VARCHAR2(3 BYTE),
     "PROJECT_NO" VARCHAR2(15 BYTE),
     "PR_NO" VARCHAR2(15 BYTE),
     "PO_NO" VARCHAR2(15 BYTE),
     "SEQ_NO" NUMBER(3,0),
     "DO_NO" VARCHAR2(15 BYTE),
     "GRN_NO" VARCHAR2(15 BYTE),
     "FREIGHT_IND" VARCHAR2(1 BYTE),
     "CURRENCY_CODE" VARCHAR2(3 BYTE),
     "CURRENCY_RATE" NUMBER(10,6),
     "IN_QTY" NUMBER(16,4),
     "OUT_QTY" NUMBER(16,4),
     "ORDER_QTY" NUMBER(16,4),
     "BAL_QTY" NUMBER(16,4),
     "ACTUAL_COST" NUMBER(16,4),
     "NEW_STD_MATERIAL" NUMBER(16,4),
     "ORI_STD_MATERIAL" NUMBER(16,4),
     "SELLING_PRICE" NUMBER(16,4),
     "FREIGHT" NUMBER(16,4),
     "HANDLING" NUMBER(16,4),
     "CUSTOM_DUTY" NUMBER(16,4),
     "WEIGHTAGE" NUMBER(16,4),
     "COST_VARIANCE" NUMBER(16,4),
     "GRN_VARIANCE" NUMBER(16,4),
     "ENTRY_USER" VARCHAR2(30 BYTE),
     "ENTRY_DATE" DATE,
     "ORIGINATOR" VARCHAR2(20 BYTE),
     "REMARKS" VARCHAR2(2000 BYTE),
     CONSTRAINT "INAUDIT_FK" FOREIGN KEY ("COMPANY_CODE", "PLANT_NO", "ITEM_NO", "LOC")
         REFERENCES ITEMLOC ("COMPANY_CODE", "PLANT_NO", "ITEM_NO", "LOC") ENABLE
);