----------------------------------------------- BOM -----------------------------------------------

CREATE TABLE BOM
(
    "COMPANY_CODE"   VARCHAR2(3 BYTE)  NOT NULL ENABLE,
    "PLANT_NO"       NUMBER(3, 0)      NOT NULL ENABLE,
    "ASSEMBLY_NO"    VARCHAR2(15 BYTE) NOT NULL ENABLE,
    "SEQ_NO"         NUMBER(3, 0)      NOT NULL ENABLE,
    "COMPONENT"      VARCHAR2(15 BYTE),
    "QTY_PER_ASSM"   NUMBER(16, 4),
    "MATL_COST"      NUMBER(16, 4),
    "LABR_COST"      NUMBER(16, 4),
    "EFFECTIVE_DATE" DATE,
    "OBSOLETE_DATE"  DATE,
    "ENGINEER"       VARCHAR2(30 BYTE),
    "REFERENCE"      VARCHAR2(30 BYTE),
    "MRP_STATUS"     VARCHAR2(1 BYTE),
    "REV_DATE"       DATE,
    "REV_NO"         NUMBER(5, 0),
    "REV_REF"        VARCHAR2(30 BYTE),
    "ENTRY_USER"     VARCHAR2(30 BYTE),
    "ENTRY_DATE"     DATE,
    "REMARKS"        VARCHAR2(2000 BYTE),
    "EQV_STATUS"     VARCHAR2(1 BYTE)
);

CREATE UNIQUE INDEX BOM_PK ON BOM ("COMPANY_CODE", "PLANT_NO", "ASSEMBLY_NO", "SEQ_NO");

ALTER TABLE BOM
    ADD CONSTRAINT BOM_PK PRIMARY KEY ("COMPANY_CODE", "PLANT_NO", "ASSEMBLY_NO", "SEQ_NO")
        USING INDEX BOM_PK ENABLE;

CREATE INDEX BOM_IDX1 ON BOM ("COMPANY_CODE", "PLANT_NO", "ASSEMBLY_NO", "COMPONENT");

CREATE INDEX BOM_IDX2 ON BOM ("COMPANY_CODE", "PLANT_NO", "ASSEMBLY_NO");