------------------ GRN TABLE CREATION ------------------

CREATE TABLE GRN
(
    "COMPANY_CODE"    VARCHAR2(3 BYTE)  NOT NULL ENABLE,
    "PLANT_NO"        NUMBER(3, 0)      NOT NULL ENABLE,
    "SUB_TYPE"        VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "GRN_NO"          VARCHAR2(15 BYTE) NOT NULL ENABLE,
    "PO_NO"           VARCHAR2(15 BYTE),
    "DO_NO"           VARCHAR2(15 BYTE),
    "SUPPLIER_CODE"   VARCHAR2(10 BYTE),
    "CURRENCY_CODE"   VARCHAR2(3 BYTE),
    "CURRENCY_RATE"   NUMBER(10, 6),
    "RECD_DATE"       DATE,
    "STATUS"          VARCHAR2(1 BYTE),
    "ENTRY_USER"      VARCHAR2(30 BYTE),
    "ENTRY_DATE"      DATE,
    "CLOSED_DATE"     DATE,
    "DOCM_TYPE"       VARCHAR2(3 BYTE),
    "REQUESTOR"       VARCHAR2(30 BYTE),
    "APPROVER"        VARCHAR2(30 BYTE),
    "APPROVAL_DATE"   DATE,
    "REQ_SUBMIT_NO"   VARCHAR2(5 BYTE),
    "REQ_SUBMIT_DATE" DATE
);

CREATE UNIQUE INDEX GRN_PK ON GRN ("COMPANY_CODE", "PLANT_NO", "SUB_TYPE", "GRN_NO");

ALTER TABLE GRN
    ADD CONSTRAINT GRN_PK PRIMARY KEY ("COMPANY_CODE", "PLANT_NO", "SUB_TYPE", "GRN_NO")
        USING INDEX GRN_PK ENABLE;

------------------ GRN DETAIL TABLE CREATION ------------------

CREATE TABLE GRNDET
(
    "COMPANY_CODE" VARCHAR2(3 BYTE)  NOT NULL ENABLE,
    "PLANT_NO"     NUMBER(3, 0)      NOT NULL ENABLE,
    "SUB_TYPE"     VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "GRN_NO"       VARCHAR2(15 BYTE) NOT NULL ENABLE,
    "SEQ_NO"       NUMBER(3, 0)      NOT NULL ENABLE,
    "ITEM_NO"      VARCHAR2(15 BYTE),
    "PART_NO"      VARCHAR2(60 BYTE),
    "LOC"          VARCHAR2(5 BYTE),
    "ITEM_TYPE"    NUMBER(2, 0),
    "PROJECT_NO"   VARCHAR2(15 BYTE),
    "PO_NO"        VARCHAR2(15 BYTE),
    "PO_REC_SEQ"   NUMBER(3, 0),
    "DO_NO"        VARCHAR2(15 BYTE),
    "SIV_NO"       VARCHAR2(15 BYTE),
    "UOM"          VARCHAR2(3 BYTE),
    "RECD_DATE"    DATE,
    "RECD_QTY"     NUMBER(16, 4),
    "RECD_PRICE"   NUMBER(16, 4),
    "PO_PRICE"     NUMBER(16, 4),
    "ISSUED_QTY"   NUMBER(16, 4),
    "LABEL_QTY"    NUMBER(16, 4),
    "STD_PACK_QTY" NUMBER(12, 6),
    "AP_RECD_QTY"  NUMBER(16, 4),
    "REMARKS"      VARCHAR2(2000 BYTE),
    CONSTRAINT GRNDET_FK FOREIGN KEY ("COMPANY_CODE", "PLANT_NO", "SUB_TYPE", "GRN_NO")
        REFERENCES GRN ("COMPANY_CODE", "PLANT_NO", "SUB_TYPE", "GRN_NO") DISABLE
);

CREATE UNIQUE INDEX GRNDET_PK ON GRNDET ("COMPANY_CODE", "PLANT_NO", "SUB_TYPE", "GRN_NO", "SEQ_NO");

ALTER TABLE GRNDET
    ADD CONSTRAINT GRNDET_PK PRIMARY KEY ("COMPANY_CODE", "PLANT_NO", "SUB_TYPE", "GRN_NO", "SEQ_NO")
        USING INDEX GRNDET_PK ENABLE;