ALTER TABLE LOC
ADD
    (   STATUS INTEGER NOT NULL,
        CREATED_BY VARCHAR2(200) NOT NULL,
        CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
        UPDATED_BY VARCHAR2(200) NOT NULL,
        UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
    );

ALTER TABLE ITEM
ADD
    (   STATUS INTEGER NOT NULL,
        CREATED_BY VARCHAR2(200) NOT NULL,
        CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
        UPDATED_BY VARCHAR2(200) NOT NULL,
        UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
    );