
CREATE TABLE UOM
(	"UOM_FROM" VARCHAR2(3 BYTE) NOT NULL ENABLE,
     "UOM_TO" VARCHAR2(3 BYTE) NOT NULL ENABLE,
     "FROM_DESCRIPTION" VARCHAR2(30 BYTE),
     "TO_DESCRIPTION" VARCHAR2(30 BYTE),
     "UOM_FACTOR" NUMBER(12,6),
     "VERSION" NUMBER DEFAULT 0 NOT NULL,
     STATUS INTEGER NOT NULL,
     CREATED_BY VARCHAR2(200) NOT NULL,
     CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
     UPDATED_BY VARCHAR2(200) NOT NULL,
     UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX UOM_PK ON UOM ("UOM_FROM", "UOM_TO");
ALTER TABLE UOM ADD CONSTRAINT UOM_PK PRIMARY KEY ("UOM_FROM", "UOM_TO")
    USING INDEX UOM_PK ENABLE;


ALTER TABLE ITEMCAT
ADD
    (
        "VERSION" NUMBER DEFAULT 0 NOT NULL,
        STATUS INTEGER DEFAULT 1 NOT NULL,
        CREATED_BY VARCHAR2(200) DEFAULT 'system' NOT NULL,
        CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATED_BY VARCHAR2(200) DEFAULT 'system' NOT NULL,
        UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
    );


CREATE TABLE INVCTL
(	"COMPANY_CODE" VARCHAR2(3 BYTE) NOT NULL ENABLE,
     "PLANT_NO" NUMBER(3,0) NOT NULL ENABLE,
     "STOCK_DEPN" NUMBER(5,2),
     "PROV_AGE" NUMBER(5,2),
     "VERSION" NUMBER DEFAULT 0 NOT NULL,
     STATUS INTEGER DEFAULT 1 NOT NULL,
     CREATED_BY VARCHAR2(200) DEFAULT 'system' NOT NULL,
     CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
     UPDATED_BY VARCHAR2(200) DEFAULT 'system' NOT NULL,
     UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX INVCTL_PK ON INVCTL ("COMPANY_CODE", "PLANT_NO");
ALTER TABLE INVCTL ADD CONSTRAINT INVCTL_PK PRIMARY KEY ("COMPANY_CODE", "PLANT_NO")
    USING INDEX INVCTL_PK ENABLE;