------------------ DOCM_NO TABLE ------------------

CREATE TABLE DOCM_NO
(
    "COMPANY_CODE"      VARCHAR2(3 BYTE)  NOT NULL ENABLE,
    "PLANT_NO"          NUMBER(3, 0)      NOT NULL ENABLE,
    "TYPE"              VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "SUB_TYPE"          VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "DESCRIPTION"       VARCHAR2(60 BYTE),
    "LAST_GENERATED_NO" NUMBER(10, 0),
    "PREFIX"            VARCHAR2(8 BYTE),
    "POSTFIX"           VARCHAR2(8 BYTE)
);

CREATE UNIQUE INDEX DOCM_NO_PK ON DOCM_NO ("COMPANY_CODE", "PLANT_NO", "TYPE", "SUB_TYPE");

ALTER TABLE DOCM_NO
    ADD CONSTRAINT DOCM_NO_PK PRIMARY KEY ("COMPANY_CODE", "PLANT_NO", "TYPE", "SUB_TYPE")
        USING INDEX DOCM_NO_PK ENABLE;